### PR TITLE
Version 3.31-04 candidate

### PR DESCRIPTION
**Pull request by codemanyak**
## Enhancement
- #953 LaTeX algorithm/pseudocode export (4 packages), instigated by Karl-Heinz Becker

## Bugfixes
- #974: Two defects on Processing definition import (one of them severe, i.e. hindering reload of generated diagram files)
- #975: StrukTeX export didn't cope well with backslashes in literals (and some other special characters)
- #977: Workaround for silent highlight error that let the execution get locked in rare cases

## Modifications
- #67: The line numbering option only used for BASIC export was made a plugin-specific option now.

### CODE REVIEW

**Comment by fesch** [comment]
Should I sill wait a bit? ;-)

**Comment by codemanyak** [comment]
Well, yes please, I will correct the export samples then and notify you when it will be done

**Comment by codemanyak** [comment]
Ok, it's done now. Ready for rollout...

**Comment by codemanyak** [comment]
Okay, I withdraw the pull request in order to check issue #977

**Comment by codemanyak** [comment]
Well, a new attempt for version 3.31-04 now with #977 workaround integrated...

**Pull request merged**
