### PR TITLE
Bugfixes -> version 3.30-08 candidate

### PR DESCRIPTION
**Pull request by codemanyak**
## Enhancements
- #842: Improved usability of the include list editor
- #855 New configurable default array/string sizes for code export

## Bugfixes and mended defects
- #828/#836: The fallback to all diagrams of an .arr file on batch export without specified entry points or contained main programs hadn't worked
- #847: Inconsistent handling of upper/lowercase operand names
- #848: Incomplete variable synchronisation with Includables
- #849: New log file name scheme change of release 3.30 ensured
- #851/1: Declarations for auxiliary variables on COBOL import
- #851/4: Provisional import of `SORT` statements from COBOL
- #851/5: Solution for the import of `PERFORM ... THRU ...` from COBOL
- #852: Case-ignorant Find & Replace substitutions failed for certain strings
- #853: Batch export with relative paths of and in .arr file had failed
- #854: Topological order of type definitions on export ensured
- #856: The dump of preferences subsets did not behave correctly
- #858: Functions in FOR-IN loop headers had not worked properly

### CODE REVIEW

**Comment by codemanyak** [comment]
Will integrate bugfix #858

**Comment by codemanyak** [comment]
Fix for #858 is in place.

**Comment by fesch** [comment]
`: error: cannot find symbol
				if (!txtIncludeList.getText().isBlank()) {
				                             ^
  symbol:   method isBlank()
  location: class String`

I think it should be "isEmpty()" ... no?

**Comment by codemanyak** [comment]
Yes, nearly. It must have been an inadvertent click on an auto-completion proposal by Eclipse again. IìsBlank()` is a Java 11 method, and as my eclipse runs on Java 11, I didn't notice. Sorry. I added a new pull request for it.

**Pull request merged**
