### PR TITLE
Version 3.30-13 candidate

### PR DESCRIPTION
**Pull request by codemanyak**
## Enhancements
- #890: Several improvements of the Turtleizer GUI (#704/#880):
  - SVG export with less annoying scale factor request;
  - menu items for CSV and SVG export disabled while turtle hasn't drawn anything;
  - new function to scroll to the coordinate origin;
  - mere moves (turtle goto instructions without visible trace) omitted on (CSV) export;
  - option to choose separator character for the CSV export;
  - stroke style for the axes of coordinates now compensates the zoom factor;
  - tooltip showing the turtle-world coordinate at current mouse position;
  - measuring function added with two possible snap modes and radius customization;
  - turtle image with higher resolution for zoom factors > 1;
  - F1 opens the help page for the Turtleizer GUI in the browser;
  - intuitive icons for several status bar components (home position, turtle status, zoom factor, snap mode).
- #893: Translator preview indication in language preference menu;
- #896: Holding the Shift key down, elements may now be dragged before the target element;

## Bugfixes
- #892: "Save as" and double-click trouble with arranged diagrams
- #894: Mechanism to fit the Turtleizer picture into canvas corrected
- #895: GUI scaling of the Turtleizer popup menu for "Nimbus" hadn't worked properly
- #896: Different cursor on readiness for moving diagrams in Arranger or diagram elements within a diagram in the Structorizer work area;
- #897: Numeric angle degeneration and endless loop risk in Turtleizer
- #898: Pre-evaluation of Turtleizer functions on execution was prone to cause syntax errors
- #900: Find & Replace failed on mere comments search, undue consideration of disabled "whole word" status. 

## Miscellaneous
- #891: Dutch locale revised and completed
- #901: Several potentially time-consuming actions now duly apply a wait cursor.

### CODE REVIEW

**Comment by codemanyak** [comment]
Just found a bug in Finde & Replace, I want to integrate the fix before the release is shipped.

**Comment by codemanyak** [comment]
Bugfix #900 is integrated

**Comment by fesch** [comment]
I'll do the release tomorrow ... just in case there will be something more to add you find ;-)

**Comment by fesch** [comment]
Im Handbuch fehlt eine Datei :-/

**Error:** 
Failed to load https://dycomasy.fisch.lu/Portals/structorizer/Files/menudiagram3.28-05_cpt.png, with network status code 203 and http status code 404

Error downloading https://dycomasy.fisch.lu/Portals/structorizer/Files/menudiagram3.28-05_cpt.png - server replied: Not Found

**Comment by codemanyak** [comment]
> I'll do the release tomorrow ... just in case there will be something more to add you find ;-)

As usual a wise decision ;-) Thanks in advance.

> 
> 
> Im Handbuch fehlt eine Datei :-/
> 
> **Error:**
> Failed to load https://dycomasy.fisch.lu/Portals/structorizer/Files/menudiagram3.28-05_cpt.png, with network status code 203 and http status code 404

There had already been a newer screen shot for it in the Files directory. Obviously I had overseen a reference to the old one. I found the place of the stale reference and just replaced it.
By the way: The reference has been stale since version 3.30-11 according to the PDF versions of the user guide...

**Pull request merged**
