### PR TITLE
Translator and translation updates adopted

### PR DESCRIPTION
**Pull request by codemanyak**

### CODE REVIEW

**Comment by fesch** [comment]
IT lang file did the conflict ;-)

**Comment by codemanyak** [comment]
Hi Bob

Am 02.08.2016 um 17:13 schrieb Bob Fisch:
> IT lang file did the conflict ;-)
>

Yes, indeed. I also merged it independently into my branch. But it seems 
the results are compatible. At least there is no conflict forecast now 
that I sent you my final pull request for today...

Pooh!

Oh just saw that you merged it already. We should still wait with 
releasing it, of course.

Greetings
Kay
-- 
Fachhochschule Erfurt
Fakultät Gebäudetechnik und Informatik
Studiengang Angewandte Informatik
Lehrgebiet Grundlagen Informatik und Betriebssysteme

PF 45 01 55, 99051 Erfurt

Telefon: 0361 6700-677
Telefax: 0361 6700-643
E-Mail: kay.guertzig@fh-erfurt.de
Internet: http://www.fh-erfurt.de

**Comment by fesch** [comment]
:-\

I said "yes" but lunched the wrong script. But hey,
I could go back easily with git ;-)
Let's try that ...


Bob

**Comment by fesch** [comment]
Okay,

lesson "checkout a given revision with git" learned :-D
That was quite easy...


Bob

**Pull request merged**
