### PR TITLE
Version 3.27-04 candidate (merged from bugfix)

### PR DESCRIPTION
**Pull request by codemanyak**
- Bugfix #468: User guide action was associated to wrong toolbar button
- Enh. #452/#459: Further revision to the mechanisms of the guided tours
- Enh. #469: Accelerator keys for Executor (Ctrl-R) and Turtleizer
- Bugfixes in COBOL import (USAGE parsing, SEARCH, EXIT)
- Issue #471: Code import error can now be copied to clipboard
- Bugfix #473: COBOL argument types failed to be generated
- Bugfix #475: Import of COBOL paragraphs broke sections
- Bugfix #480: Import of COBOL level-77 data and record array initialization
- Bugfix #483: Option to suppress mere variable declarations on COBOL import
- Bugfix #485: Workaround for intrinsic COBOL functions
- Bugfix #486: Return mechanism in imported COBOL functions enforced
- Enh. #487: New display mode to hide (collapse) declaration sequences
- Enh. #87: Insertion of elements enabled on multiple selections
- Enh. #425: Simple find mechanism in Translator and key sensitivity
- Enh. #491: Translator: tooltips show master texts too long for the column
- Enh. #492: Configurable designations of element types
- Issues #493, #494: COBOL import improved w.r.t. SEARCH

### CODE REVIEW

**Comment by GitMensch** [comment]
@codemanyak Is #87 really part of this? I assume there was just the leading "4" missing?

**Comment by codemanyak** [comment]
@GitMensch 
> Is #87 really part of this? I assume there was just the leading "4" missing?

You are right: I did not mean #87 (though this issue had been mentioned on occasion of #487 because of some similarities), I actually wanted to refer to #38 (which had the number KGU#87 on my personal tracking agenda). I simply mixed them up.

**Comment by GitMensch** [comment]
@codemanyak ok, but I'm still confused as #38 was included in an earlier release - wasn't it?

**Comment by codemanyak** [comment]
@GitMensch 
> I'm still confused as #38 was included in an earlier release - wasn't it?

It was, but I "accidently" realized on implementing #487 that I could easily overcome a functional shortcoming of #38. So I didn't bother to open a new issue but just referred to the old one. This may not be quite clean but was pragmatic and clear enough, I thought, as it was a pretty specific enhancement request (whereas e.g. in the giant COBOL import realm a reference to #354 wouldn't really be helpful.)

**Comment by GitMensch** [comment]
I think it still can be seen as clean to reference an "old" issue as long as something about the shortcoming and change is noted in the issue ;-)

**Pull request merged**
