### PR TITLE
Version 3.28-06 candidate (pulled from bugfix)

### PR DESCRIPTION
**Pull request by codemanyak**
- Issue #561 - new design of the statistics in Attribute Inspector
- Bugfix #562 - Wrong "origin" attribute for loaded older diagrams
- Enh. #563 - Simplified record initializers (smarter evaluation)
- Bugfix #564 - code export defects with nested array initializers
- Attributation of syntax highlighting to diagrams simplified
- Bugfix #565 - Translator didn't open; updates in Russian locale
- Issue #566 - Version retrieval adapted to new home page URL (https)

### CODE REVIEW

**Comment by fesch** [comment]
upload done

**Comment by codemanyak** [comment]
There's an issue with the product download, though: It doesn't work via clicking with the left mouse key as usual, but only via the context menu (which means that is works at least somehow).

**Comment by fesch** [comment]
What download link are you referring to?

**Comment by codemanyak** [comment]
Well, the "latest version" zip files from the Download page (for Windows & Linux, for Mac) as well as the SOURCE CODE packages. The Jnlp download works both from the WebStart menu entry and from the Download page.

**Comment by fesch** [comment]
fixed (was a http link)

**Comment by codemanyak** [comment]
Ah, well, with the Internet Explorer the downloads work (after some detention), so it seems to be bound to the Firefox browser that the zip downloads are ignored on left button click. (Before the https switch - may be pure coincidence or not - it had always worked wth Firefox as well.)

**Comment by codemanyak** [comment]
And there is a dramatic difference with the page source code that is shown by IE (complete) and Firefox, where I am shown just this (note the empty body!):
```html
<html>
 <head>
  <title>:: STRUCTORIZER ::</title>
  <link rel="SHORTCUT ICON" href="favicon.ico">
<meta name="google-site-verification" content="jfg4DM3lgOj6_dEmGG4a0O6nyerC0FiXnHtLW0sI2_Y" />
 </head>

 <frameset rows="100%,*" frameborder="0" framespacing="0" border="0">
  <frame name="Window" src="index.php" scrolling="yes">
  <frame name="Robots" src="robots.php" scrolling="yes">
 </frameset>

 <body>
 </body>

</html>
```

**Comment by codemanyak** [comment]
Thanks for the fixing, now it all works with Firefox, too. - Maybe, I had still tried with the cached page.

**Pull request merged**
