### PR TITLE
Version 3.32-12 candidate

### PR DESCRIPTION
**Pull request by codemanyak**
There are enough bugfixes waitng for integration now, I think, it has been a long time since the last version. Some enhancements will still have to wait, however.
## Bugfixes / improvements:
- #678 - a side effect had compromised pointer type import.
- #739 - had been forgotten on C# export.
- #809, the second one modified (`return val` → `exit val`)
- #1066 precision for CALLs improved.
- #1067
- #1071
- #1072
- #1073
- #1074
- #1028 + #1076
- #1077: Javadoc warnings avoided by annotation completion
- #1082
- Undue #1083 with `-p Pascal ...`
- #1085
- #1086
- #1089
- #1091 
- #1092

### CODE REVIEW

**Comment by codemanyak** [comment]
The fix for #1089 is to be included.

**Comment by codemanyak** [comment]
More fixes provided (for #678, #739, #1091, #1092).

**Review by fesch — APPROVED** [review]

**Comment by codemanyak** [comment]
Hi Bob, it seems that the build hadn't worked yet. There is no new download from the Structorizer page.

**Comment by fesch** [comment]
I did not do the upload ... too many things to do at once in school ;)

**Pull request merged**
