### PR TITLE
Release 3.31 candidate

### PR DESCRIPTION
**Pull request by codemanyak**
## Enhancements
- #410: Java import implemented (+ new diagram field "namespace")
- #932: "Processing" source code import implemented [Enh. requ. by Karl-Heinz Becker]
- #943: Used Java home path now also displayed in the About dialog

## Bugfixes
- #419: "(Re-)break lines" missed to redraw the reshaped diagram
- #905: Diagram redrawing after Analyser Preference changes fixed
- #945: "Disabled" status of PARALLEL elements had not been saved
- #946: Structorizer could get locked on certain assignment texts
- #947: Executor had not detected cyclic inclusion, but spun down (endless recursion)

## Miscellaneous
- #944: Upgrade to Java 11 announced (version hint on starting Structorizer)

### CODE REVIEW

**Comment by fesch** [comment]
Class "CodeParser" is missing in the repo I think ... :-/

**Comment by codemanyak** [comment]
Well, umh, no. CodeParser.java is where it ought to be. So it may rather be a compilation error that hindered the creation of CodeParser.class. What exactly is the error message you are likely to have got telling?

**Comment by fesch** [comment]
Ahhh ... illegal charater in JavaParser.java before the first /*
Strange, that all this produced the other error ...

**Comment by codemanyak** [comment]
Oh, maybe the UTF-8-BOM sequence is still at the beginning of the file. Eclipse didn't bother.

**Comment by fesch** [comment]
compiled & online

**Pull request merged**
