### PR TITLE
Version 3.28-02 candidate (bugfix #451, #463, #512, #525, #526, #527, #528, #529, #533)

### PR DESCRIPTION
**Pull request by codemanyak**
- Bugfix #525: Defective test coverage detection for recursive routines,
      lacking operation counts on input, output, and jump instructions fixed.
- Issue #512: Arranger zoom compensation for PNG export was flawed
- Bugfix #526: On re-saving the renaming of the temp. file could fail (Linux) 
- Issue #527: More helpful Executor messages on index range violations
- Issue #463: Console output replaced by configurable logging
- Bugfix #528: Analyser check of record component access mended
- Issue #529: Concurrency on drawing diagrams during execution solved (more stable drawing)
- Bugfix #451: Java version test in shell start scripts revised
- Bugfix #533: Import of struct types from C files was dysfunctional

### CODE REVIEW

**Comment by codemanyak** [comment]
Hi, Bob,
I forgot to add the remark that an additional file logging.properties should be placed in the directory Structorizer/Structorizer.app/Contents/java (next to the Jar) file on delivery.
I'll put in in the root directory of the Git project. I don't know how you might configure the release script such that it may be copied to that directory. This will work for the installable desktop version. I added some piece of code in order to find out where the Structorizer would look for this file in a WebStart envionment (I have no idea so far).

**Comment by codemanyak** [comment]
Hi Bob,
Thanks for merging. Sorry for having virtually been off-line so long. I saw, however, that version 3.28-02 has not become available on the Structorizer homepage so far. Now I wonder, is there some trouble on building the deliverable version or may you be waiting for some signal from me?
So just some reassuring information: The mentioned configuration file "logging.properties" had already been placed in the root directory. If it wouldn't not found then Structorizer will simply fall back to the default setting of the Java product, such that there won't be a log file but all logging from the INFO level on will be written to the console, which might be a little much on Linux systems but wouldn't visible on a Windows platform unless Structorizer were started via the "Structorizer.bat" script. So if there is some show-stopper I'm not aware off, please let me know.

**Comment by fesch** [comment]
I simply was too tired yesterday, no worry ;)

**Comment by codemanyak** [comment]
Hi Bob, thanks. What failed, however, is the placement of the file "logging.properties" (from the project root) in folder "Structorizer.app/Contents/Java". It's missng in the downloadable zip. Do you think you could mend this? Thanks in advance.

**Comment by fesch** [comment]
Ups ... putting the file into the directory before doing the clean was a bad idea.
It is now fixed ...

**Comment by codemanyak** [comment]
@fesch 
I wrote:
> I added some piece of code in order to find out where the Structorizer would look for this file in a WebStart envionment (I have no idea so far).

My piece of code signalled that the logging.properties file is expected in the location http://structorizer.fisch.lu/webstart. Well, I might have gessed this in the first place, but now I know.
So it might be worth a try for you to place a copy of the file logging.properties just there on your home page. This is not very helpful for user configuration, of course, but would at least allow to provide the default logging configuration for Structorizer, I hope. Would you be so kind to try to place it here?

If it works for subsequent starts then I will prepare a way automatically to copy this file on Structorizer start to a local place (preferrably `<home>`/.structorizer, if there isn't one already) where further starts would look for it first, such that the user might modify the copy at that position. I hope it won't violate some browser sandbox.

Thanks in advance.

**Comment by fesch** [comment]
The file has now been added here:

structorizer.fisch.lu/webstart/logging.properties

**Pull request merged**
