### PR TITLE
Version 3.30-16 candidate

### PR DESCRIPTION
**Pull request by codemanyak**
## Enhancements: Several usability improvement efforts
- #915: Functional upgrade for the new CASE element editor
- #928: New Analyser check against structured CASE choice value (like in editor)
- #929: Translator usability improved with locale button context menus, temporary icon changes on shift; locale reset mechanism fixed

## Bugfixes
- #893: Translator preview indicator in the language menu enforced
- #930: Wrong CASE branch width with broken selector lines
- #931: Inadvertent font changes in element editors on font resizing

### CODE REVIEW

**Comment by fesch** [comment]
@codemanyak : Error, cannot find symbol "CaseEditHelper" in *Diagram.java" and "InputBoxCase.java".

Did you forget to add it?

**Comment by codemanyak** [comment]
Yes, of course, I am sorry! Just added it to source control.

**Comment by fesch** [comment]
I still can't find it :-/

**Comment by codemanyak** [comment]
This time I forgot the pull request... (just amnesia or Alzheimer already?)

**Pull request merged**
