### PR TITLE
structurizer.sh: check for java instead of jar

### PR DESCRIPTION
**Pull request by GitMensch**
and adjusted file check

### CODE REVIEW

**Comment by GitMensch** [comment]
... same adjustments should be done to Arranger.sh

**Comment by fesch** [comment]
After your comments of yesterday, I've done the same changes already.
Yes, also to arranger.sh, so this is why I do not merge this PR.

**Comment by GitMensch** [comment]
@fesch: The current version does not have the same changes, while it checks for `java` binary it still says "jar" and the file check is different, too.
Should I redo these changes to master and create a new PR?

**Comment by fesch** [comment]
Ups ... updated some seconds ago ;)

**Comment by GitMensch** [comment]
@fesch This only leaves

```sh
# check for jar in PATH
```

and possibly the file check. Can you please explain why you've did it that way (which I've never encountered before) instead of the direct "is this a file" check?

**Comment by fesch** [comment]
> Can you please explain why you've did it that way (which I've never encountered before) instead of the direct "is this a file" check?

Hummm ... probably because I misunderstood in a first time what the previous check was supposed to do  :-) ;-)

**Pull request closed without merging**
