### PR TITLE
Version 3.32-11 candidate (1066 name completion mechanism)

### PR DESCRIPTION
**Pull request by codemanyak**
## Enhancements
- #1066 (Content assist)
- Executor, Analyser, and code generators now accept index lists like in **myArray[i,j]**
- TeX (algo/StrukTex) export files now ensured to contain the Structorizer version no.

## Bugfixes
- #1059
- #1065, right mouse click into Arranger Index may override a previous single selection now
- #1067 
- #1068

### CODE REVIEW

**Comment by fesch** [comment]
`lu\fisch\structorizer\elements\Element.java:3838: warning: as of release 10, 'var' is a restricted local variable type and cannot be used for type declarations or as the element type of an array
`
Any idea what this means?

**Comment by fesch** [comment]
Looks like compiling with Java-8 is no longer possible :-(

**Comment by fesch** [comment]
Okay, got it fixed ...

**Comment by codemanyak** [comment]
> Looks like compiling with Java-8 is no longer possible :-(

You are right. As already mentioned for the decision to chnage the installation requirement from Java 8 to Java 11, the number of deprecation warnings and incompatibilities had been growing. Now, after having done the upgrade step, I didn't see a reason further to avoid all linguistic innovations of Java 9 through 11. The "var" declaration is pretty convenient... (feels like Structorizer 😁 )

**Comment by fesch** [comment]
... but it breaks Unimozer, which can't move to Java-11 and depends on Structorize .... :-(

**Comment by codemanyak** [comment]
> ... but it breaks Unimozer, which can't move to Java-11 and depends on Structorize .... :-(

Oops. I was not aware that Unimozer is still updating its Structorizer component on Java 8 stage. But then you will possibly experience more trouble on run-time, I am afraid, because the code now also contains some methods like `String::isBlank()` or `String::repeat()`, `modelToView2d()` etc. :-/  I can't count all occurrences anymore...

**Comment by fesch** [comment]
Only the "var" thing was blocking ... strange, but true ;-)

**Comment by codemanyak** [comment]
> Only the "var" thing was blocking ... strange, but true ;-)

Oh we experienced this already. The "var" declaration is a syntactic problem whereas the methods provided by younger versions aren't. They are the land mines the virtual machine will be stepping on...

**Pull request merged**
